---
- traffic: server
  ip: "192.168.56.10"
  ram: "4"
  vcpu: "1"
  platform: docker

- traffic: client
  ip: "192.168.57.10"
  ram: "4"
  vcpu: "1"
  platform: docker

            
- topology:
    type: "tree"
    depth: "3"
    branching: "3"
    routers: "7"
