---
- traffic: server
  ip: "10.0.0.1"
  ram: "2048"
  vcpu: "2"
  platform: vm

- traffic: client
  ip: "10.0.0.2"
  ram: "2048"
  vcpu: "2"
  platform: vm

            
- topology:
    type: "tree"
    depth: "3"
    branching: "2"
    max_switches: "8"
