---
- traffic: server
  ip: "192.168.0.10"
  ram: "2048"
  vcpu: "1"
  platform: vm

- traffic: client
  ip: "192.168.11"
  ram: "2048"
  vcpu: "1"
  platform: vm

            
- topology:
    type: "tree"
    depth: "3"
    branching: "2"
    max_switches: "10"
    delay: "900"
